name: Fetch Australia OSM data

on:
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
          
      - name: Install packages
        run: pip install quackosm[cli]

      - name: Download Australian OSM data
        run: wget -qo ./australia.osm.pbf https://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf

      - name: Convert to geoparquet
        run: quackosm ./australia.osm.pbf
        
      - name: Commit artifacts
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          file_pattern: './*.geoparquet'
